export const blogList = [
  {
    id: 1,
    title: 'Scholarship to the disable students (Director, Social Defence) :    ',
    category: 'Disable Students ',
    subCategory: ['Scholarship', 'children', 'economically weaker class'],
   heading:['Purpose :'],
    description:['This scheme is implemented with a view to impart education to the Disable children of economically weaker guardians to purchase necessary materials for their education and to instigate education among them, thereby minimizing the educational expenditure to some extent.'],
    point1:['(1) Eligibility criteria for availing Disable scholarship:-'],
    subpoint1:['The percentage of handicapness of the student must not be below 40%,',
    'Must have passed the last annual exam with at least 40% marks.',
    'Regular satisfactory attendance in the relevant studies is necessary.',
    'The annual family income of the guardian of the Disable students studying in Std. I to VII should not be more than Rs. 50,000/-.',
    'The annual family income of the guardians of the Disable student studying beyond Std. VIII should not be more than Rs. 50,000/- and must be a holder of Disable Identity Card,'],
point2:['(2) How much Disable Scholarship is receivable ? :-'],
subpoint2:['The Disable students studying in Std. I to VII are paid Rs. 1,000/- per annum.',
    'The Disable students studying beyond Std. VIII are paid Rs. 1,500/- or maximum of Rs. 5,000/- per annum.',
    'The Disable Scholarship is sent to the respective primary school b y the Taluka Development Officer.',
    'The Disable Scholarship to the students of beyond Std. VIII is sent to the Principal of the School or College.'],
    point3:['(3) Regarding obtaining of Application forms of Disable Scholarship :-'],
  subpoint3:[  'Forms are available at the beginning of academic activities every year from 15th June to 31st August and to be returned duly filled-in in all respects by the end of August.',
    'Renewal or Fresh application forms are issued against the letter from the School or College.',
    'Application Forms are available at free of cost from District Social Security Officer.',
    'To submit the forms to the Office of the District Social Security Officer after getting it filled in the prescribed form within the time limit is the responsibility of the Principal of the School/College.'],
 point4:['(4) Documents to be submitted alongwith the Application for Disable Scholarship.'],
    subpoint4:['The Identity Card of the Disable persons and the percentage Certificate of Specialist Doctor of relevant Department,',
    'Certificate issued by a competent authority showing the Annual income of the guardian.',
    'Attested copy of the final result of last year.',
    'Application Forms to be sent through relevant educational institutions with complete details.',
    'Applications of students belong to SC, ST, Baxi Panch or General must be sent with separate statement.'],
  point5:['(5) When the Disable Scholarship is not payable :'],
  subpoint5:[  'If the Disable students is irregular in School, College or educational Institutions,',
    'If the student has left the studies,',
    'If the student dies in an accident,',
    'If in receipt of Scholarship of Backward Class or Scheduled Tribes.',
    'If handicapness is less than 40%,',
    'If the marks obtained is less than 40%',
    'If the income is more than Rs. 50,000/- per annum.',
    'The power to sanction the Scholarship is entrusted to District Social Security Officer.'],
  
    authorName: 'Lalani Hiren',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'September 10, 2022',
    cover: '/assets/images/diable_st.jpg',
  },
  {
    id: 2,
    title: 'Milan Places That Highlight The City',
    category: 'travel',
    subCategory: ['vacation', 'holidays', 'sight seeing'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/f67396fc3cfce63a28e07ebb35d974ac.jpg',
  },
  {
    id: 3,
    title: 'Online Shopping – An Alternative to Shopping in the Mall',
    category: 'shopping',
    subCategory: ['e-commerce store', 'clothing', 'shopping store'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/fQwuyKJ9qxjSbr6REcgtmW-1200-80.jpg',
  },
  {
    id: 4,
    title: 'ADVENTURE IN YOU',
    category: 'adventure',
    subCategory: ['adrenaline', 'stay-fit', 'lifestyle'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/graphic-design-trends.png',
  },
  {
    id: 5,
    title: 'Loaded BBQ Baked Potatoes',
    category: 'cooking',
    subCategory: ['bbq', 'food', 'lifestyle'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/make-it-personal.jpg',
  },
  {
    id: 6,
    title: 'Beyond the Beach',
    category: 'travel',
    subCategory: ['beaches', 'sea', 'holidays'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover:
      '/assets/images/Purple-Combination-colors-graphic-design-predictions-1024x576-1024x576.jpg',
  },
  {
    id: 7,
    title: 'Art & Perception',
    category: 'art',
    subCategory: ['skill', 'design', 'passion'],
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    authorName: 'John Doe',
    authorAvatar: '/assets/images/author.jpg',
    createdAt: 'June 03, 2021',
    cover: '/assets/images/Synthwave-Postmodern.jpg',
  },
];
